const SUPABASE_URL='https://lepvlmclsbciwvhxyktf.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_V_s6ONo_RtLR3sR96asPJw_M92v98vR';
const APP_ID='APP-001';
const CLOUD_SCHEMA_VERSION=2;
const cloud=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let cloudUser=null,cloudRevision=0;

function cloudClone(v){return JSON.parse(JSON.stringify(v))}
function cloudId(prefix){const raw=((window.crypto&&crypto.randomUUID)?crypto.randomUUID():Math.random().toString(16).slice(2)+Date.now().toString(16)).replace(/-/g,'');return prefix+'-'+raw.slice(0,8).toUpperCase()}
function cloudIsoDate(d=new Date()){const x=new Date(d),y=x.getFullYear(),m=String(x.getMonth()+1).padStart(2,'0'),day=String(x.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function cloudMonth(d=new Date()){return cloudIsoDate(d).slice(0,7)}
function cloudAddDays(value,days){const d=value instanceof Date?new Date(value):new Date(String(value||cloudIsoDate())+'T12:00:00');d.setDate(d.getDate()+Number(days||0));return cloudIsoDate(d)}
function cloudDaysSince(v){if(!v)return null;const d=new Date(String(v).slice(0,10)+'T12:00:00'),n=new Date();if(Number.isNaN(d.getTime()))return null;return Math.max(0,Math.floor((new Date(n.getFullYear(),n.getMonth(),n.getDate())-new Date(d.getFullYear(),d.getMonth(),d.getDate()))/86400000))}
function cloudBool(v,f=false){if(v===true||v===false)return v;if(v==null||v==='')return f;return ['да','true','1','yes'].includes(String(v).trim().toLowerCase())}
function cloudUnit(v){return String(v||'').toLowerCase().includes('кг')||String(v||'').toLowerCase()==='kg'?'кг':'шт.'}
function cloudMinQty(u){return cloudUnit(u)==='кг'?0.1:1}
function cloudQty(v,u){const x=Math.max(0,rawNumber(v));return cloudUnit(u)==='кг'?Math.round((x+Number.EPSILON)*10)/10:Math.round(x)}
function cloudStep(u){return cloudUnit(u)==='кг'?(Number(state?.settings?.kgStep)||0.1):1}
function cloudCeilQty(v,u){const x=Math.max(0,rawNumber(v));if(x<=0)return 0;const st=cloudStep(u);return st===1?Math.ceil(x):Math.round((Math.ceil((x-1e-9)/st)*st+Number.EPSILON)*1000)/1000}
function cloudStatus(stock,target,almost){const s=rawNumber(stock),t=Math.max(0,rawNumber(target));if(s<=0)return 'закончилось';if(almost)return 'заканчивается';if(t<=0)return 'есть достаточно';return (s/t)*100<Math.max(1,rawNumber(state?.settings?.lowStockPercent)||20)?'заканчивается':'есть достаточно'}
function cloudRecomputeProduct(p){const u=cloudUnit(p.pack||p.unit),days=Math.max(0,rawNumber(p.daysSupply)),fallback=u==='кг'?1:(days>0?Math.max(1,Math.ceil(7/days)):1),target=Math.max(cloudMinQty(u),cloudQty((p.weeklyTarget===''||p.weeklyTarget==null)?fallback:p.weeklyTarget,u)),stock=cloudQty(p.currentStock,u),almost=u==='шт.'&&stock>0&&cloudBool(p.almostEmpty,false),effective=almost?Math.max(0,stock-1):stock;p.pack=p.unit=u;p.weeklyTarget=target;p.currentStock=stock;p.almostEmpty=almost;p.effectiveStock=effective;p.recommendedQty=cloudCeilQty(Math.max(0,target-effective),u);p.homeStatus=cloudStatus(stock,target,almost);p.daysSincePurchase=cloudDaysSince(p.lastPurchase);p.price=p.price===''||p.price==null?'':Math.max(0,rawNumber(p.price));p.category=p.category||'';p.note=p.note||'';p.active=p.active||'да';p.mainStore=p.mainStore||'';return p}
function cloudEnrichBasketItem(i){const p=(state.products||[]).find(x=>x.productId===i.productId)||{},u=cloudUnit(p.unit||p.pack||i.unit);i.unit=u;i.category=p.category||i.category||'';i.weeklyTarget=cloudQty(p.weeklyTarget??i.weeklyTarget,u);i.currentStock=cloudQty(p.currentStock??i.currentStock,u);i.recommendedQty=cloudQty(p.recommendedQty??i.recommendedQty,u);i.qty=cloudQty(i.qty,u);i.unitPrice=i.unitPrice===''||i.unitPrice==null?'':Math.max(0,rawNumber(i.unitPrice));i.sum=Math.round((rawNumber(i.qty)*rawNumber(i.unitPrice)+Number.EPSILON)*100)/100;i.storeId=i.storeId||'';i.storeName=i.storeName||'';i.source=i.source||'вручную';i.status=i.status||'активно';i.note=i.note||'';return i}
function cloudNextShopping(){const n=new Date(),day=n.getDay(),delta=day===6?0:day===0?6:6-day,sat=new Date(n.getFullYear(),n.getMonth(),n.getDate());sat.setDate(sat.getDate()+delta);const sun=new Date(sat);sun.setDate(sun.getDate()+1);return{start:cloudIsoDate(sat),end:cloudIsoDate(sun)}}
function cloudRecompute(){if(!state)return state;state.app=Object.assign({title:'Продуктовая корзина',version:'1.0'},state.app||{},{runtime:'github-pages+supabase'});state.currentMonth=cloudMonth();state.settings=state.settings||{};state.settings.lowStockPercent=Math.min(100,Math.max(1,Math.round(rawNumber(state.settings.lowStockPercent)||20)));const allowed=[0.1,0.2,0.3,0.4,0.5],ks=rawNumber(state.settings.kgStep);state.settings.kgStep=allowed.includes(ks)?ks:0.1;state.settings.stockColumns=Object.assign({unit:false,weeklyTarget:false,remaining:true,toBuy:true,lastPurchase:false,status:true},state.settings.stockColumns||{});state.settings.stockGroupMode=state.settings.stockGroupMode==='category'?'category':'alphabet';state.settings.basketStoreId=state.settings.basketStoreId||state.basketStoreId||'';state.basketStoreId=state.settings.basketStoreId;state.categories=Array.isArray(state.categories)?state.categories:[];state.units=['шт.','кг'];state.products=(state.products||[]).filter(p=>String(p.active||'да').toLowerCase()!=='нет').map(cloudRecomputeProduct);state.stores=(state.stores||[]).filter(s=>String(s.active||'да').toLowerCase()!=='нет');state.prices=state.prices||[];state.basket=(state.basket||[]).map(cloudEnrichBasketItem);state.basketRemoved=(state.basketRemoved||[]).map(cloudEnrichBasketItem);state.purchases=state.purchases||[];state.purchaseItems=state.purchaseItems||[];state.cashback=[];const shortage=state.products.filter(p=>rawNumber(p.recommendedQty)>0).sort((a,b)=>rawNumber(b.recommendedQty)-rawNumber(a.recommendedQty)||String(a.name).localeCompare(String(b.name),'ru'));state.soon=shortage;state.nextShopping=cloudNextShopping();const total=Math.round(((state.basket||[]).reduce((s,i)=>s+rawNumber(i.qty)*rawNumber(i.unitPrice),0)+Number.EPSILON)*100)/100;state.summary={ending:state.products.filter(p=>p.homeStatus==='заканчивается').length,ended:state.products.filter(p=>p.homeStatus==='закончилось').length,shortageProducts:shortage.length,recommendedUnits:Math.round((shortage.reduce((s,p)=>s+rawNumber(p.recommendedQty),0)+Number.EPSILON)*100)/100,basketItems:state.basket.length,basketTotal:total,expectedCashback:0,effectiveCost:total};const grouped={};state.basket.forEach(i=>{const k=i.storeId||'NO_STORE';(grouped[k]=grouped[k]||[]).push(i)});state.storeSummaries=Object.entries(grouped).map(([sid,items])=>{const st=state.stores.find(s=>s.storeId===sid),sum=Math.round((items.reduce((a,x)=>a+rawNumber(x.sum),0)+Number.EPSILON)*100)/100;return{storeId:sid==='NO_STORE'?'':sid,name:st?.name||items[0]?.storeName||'Без магазина',itemCount:items.length,total:sum,cashback:0,effective:sum}}).sort((a,b)=>b.total-a.total);state.meta=Object.assign({schemaVersion:CLOUD_SCHEMA_VERSION},state.meta||{});return state}

async function cloudLoadState(){if(!cloudUser)throw new Error('Сначала войдите в приложение');const{data,error}=await cloud.from('mini_app_state').select('state,revision,schema_version').eq('app_id',APP_ID).maybeSingle();if(error)throw error;if(!data)throw new Error('Для APP-001 не найдены данные в облаке');cloudRevision=Number(data.revision)||0;state=cloudClone(data.state||{});cloudRecompute();return state}
async function cloudPersist(label=''){if(!cloudUser)throw new Error('Нет активного входа');cloudRecompute();const next=cloudRevision+1,{data,error}=await cloud.from('mini_app_state').update({state,schema_version:CLOUD_SCHEMA_VERSION,revision:next,updated_at:new Date().toISOString()}).eq('app_id',APP_ID).eq('revision',cloudRevision).select('revision').maybeSingle();if(error)throw error;if(!data){await cloudLoadState();throw new Error('Данные изменились на другом устройстве. Загружена свежая версия — повторите изменение.')}cloudRevision=Number(data.revision)||next;if(label)await cloudBackup(label);return state}
async function cloudBackup(label){if(!cloudUser)return;const{error}=await cloud.from('mini_app_backups').insert({user_id:cloudUser.id,app_id:APP_ID,schema_version:CLOUD_SCHEMA_VERSION,revision:cloudRevision,label:String(label||''),state});if(error)console.warn('Backup warning',error)}
async function cloudSignIn(e){e.preventDefault();const f=e.target,btn=f.querySelector('button[type=submit]');btn.disabled=true;document.getElementById('authError').textContent='';try{const{data,error}=await cloud.auth.signInWithPassword({email:f.email.value.trim(),password:f.password.value});if(error)throw error;cloudUser=data.user;await cloudStart()}catch(err){document.getElementById('authError').textContent=err.message||String(err)}finally{btn.disabled=false}}
async function cloudSignOut(){await cloud.auth.signOut();cloudUser=null;state=null;cloudRevision=0;document.getElementById('authGate').classList.add('open');document.getElementById('cloudUserBadge').hidden=true}
async function cloudStart(){const{data:{session}}=await cloud.auth.getSession();if(!session){document.getElementById('authGate').classList.add('open');return}cloudUser=session.user;document.getElementById('authGate').classList.remove('open');const badge=document.getElementById('cloudUserBadge');badge.hidden=false;document.getElementById('cloudUserEmail').textContent=cloudUser.email||'Выполнен вход';await loadState()}
async function bootCloud(){document.getElementById('authForm').addEventListener('submit',cloudSignIn);const{data:{session}}=await cloud.auth.getSession();if(session){cloudUser=session.user;await cloudStart()}else document.getElementById('authGate').classList.add('open');cloud.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){cloudUser=null;document.getElementById('authGate').classList.add('open')}})}

function cloudSyncAutomaticBasket(reviveDeleted=false){const store=state.stores.find(s=>s.storeId===state.settings.basketStoreId)||null,activeByPid=new Map((state.basket||[]).map(i=>[i.productId,i])),removedByPid=new Map((state.basketRemoved||[]).map(i=>[i.productId,i]));state.products.forEach(p=>{cloudRecomputeProduct(p);const rec=rawNumber(p.recommendedQty),existing=activeByPid.get(p.productId),removed=removedByPid.get(p.productId);if(existing){existing.storeId=store?.storeId||'';existing.storeName=store?.name||'';existing.weeklyTarget=p.weeklyTarget;existing.currentStock=p.currentStock;existing.recommendedQty=p.recommendedQty;if(String(existing.status).toLowerCase()==='активно'&&String(existing.source).toLowerCase()==='авто'){if(rec<=0){state.basket=state.basket.filter(x=>x!==existing);existing.status='удалено';state.basketRemoved=state.basketRemoved||[];state.basketRemoved.push(existing)}else{existing.qty=cloudQty(rec,p.unit);if(existing.unitPrice===''||existing.unitPrice==null)existing.unitPrice=p.price||''}}return}if(rec<=0)return;if(removed){if(!reviveDeleted)return;state.basketRemoved=state.basketRemoved.filter(x=>x!==removed);removed.status='активно';removed.source='авто';removed.qty=cloudQty(rec,p.unit);removed.storeId=store?.storeId||'';removed.storeName=store?.name||'';removed.unitPrice=removed.unitPrice||p.price||'';removed.weeklyTarget=p.weeklyTarget;removed.currentStock=p.currentStock;removed.recommendedQty=p.recommendedQty;state.basket.push(removed);return}state.basket.push(cloudEnrichBasketItem({basketItemId:cloudId('BKT'),productId:p.productId,name:p.name,qty:cloudQty(rec,p.unit),storeId:store?.storeId||'',storeName:store?.name||'',unitPrice:p.price||'',source:'авто',status:'активно',addedAt:new Date().toISOString(),note:'',weeklyTarget:p.weeklyTarget,currentStock:p.currentStock,recommendedQty:p.recommendedQty,unit:p.unit,category:p.category||''}))});cloudRecompute()}
function cloudUpsertPrice(product,price,storeId){const val=Math.max(0,rawNumber(price));product.price=val||'';if(!storeId)return;const ex=(state.prices||[]).find(r=>r.productId===product.productId&&r.storeId===storeId);if(ex){ex.price=val||'';ex.updatedAt=new Date().toISOString()}else(state.prices=state.prices||[]).push({priceId:cloudId('PRC'),productId:product.productId,storeId,price:val||'',updatedAt:new Date().toISOString(),main:'',note:''})}
function cloudAddManualProductToBasket(p,qty,priceOverride){const u=p.unit,store=state.stores.find(s=>s.storeId===state.settings.basketStoreId)||null;let ex=state.basket.find(i=>i.productId===p.productId),removed=state.basketRemoved.find(i=>i.productId===p.productId);const price=(priceOverride===''||priceOverride==null)?rawNumber(p.price):Math.max(0,rawNumber(priceOverride));qty=cloudQty(qty,u);if(ex){ex.qty=cloudQty(rawNumber(ex.qty)+qty,u);ex.unitPrice=price||'';ex.source='вручную';ex.status='активно';return ex}if(removed){state.basketRemoved=state.basketRemoved.filter(x=>x!==removed);ex=removed;ex.qty=qty;ex.unitPrice=price||'';ex.source='вручную';ex.status='активно';state.basket.push(ex);return ex}ex={basketItemId:cloudId('BKT'),productId:p.productId,name:p.name,qty,storeId:store?.storeId||'',storeName:store?.name||'',unitPrice:price||'',source:'вручную',status:'активно',addedAt:new Date().toISOString(),note:'',weeklyTarget:p.weeklyTarget,currentStock:p.currentStock,recommendedQty:p.recommendedQty,unit:u,category:p.category||''};state.basket.push(cloudEnrichBasketItem(ex));return ex}

function cloudApplyBasketDraft(payload){payload=payload||{};const store=state.stores.find(s=>s.storeId===(payload.storeId||''))||null;state.settings.basketStoreId=store?.storeId||'';state.basketStoreId=state.settings.basketStoreId;const existing=[...(state.basket||[]),...(state.basketRemoved||[])],map=new Map(existing.map(i=>[i.basketItemId,i])),latest=new Map(existing.map(i=>[i.productId,i])),active=[],removed=[];(payload.items||[]).forEach(raw=>{const p=state.products.find(x=>x.productId===raw.productId);if(!p)return;let i=map.get(raw.basketItemId)||latest.get(raw.productId)||{};if(!i.basketItemId||String(i.basketItemId).startsWith('TMP-'))i.basketItemId=cloudId('BKT');i.productId=p.productId;i.name=p.name;i.qty=cloudQty(raw.qty,p.unit);i.unitPrice=Math.max(0,rawNumber(raw.price));i.storeId=store?.storeId||'';i.storeName=store?.name||'';i.source=raw.source||i.source||'вручную';i.status=['активно','собрано','удалено'].includes(String(raw.status).toLowerCase())?String(raw.status).toLowerCase():'активно';i.addedAt=i.addedAt||new Date().toISOString();i.weeklyTarget=p.weeklyTarget;i.currentStock=p.currentStock;i.recommendedQty=p.recommendedQty;i.unit=p.unit;i.category=p.category||'';i.sum=Math.round((rawNumber(i.qty)*rawNumber(i.unitPrice)+Number.EPSILON)*100)/100;if(i.status==='удалено')removed.push(i);else{active.push(i);cloudUpsertPrice(p,i.unitPrice,store?.storeId||'')}});state.basket=active;state.basketRemoved=removed;cloudRecompute()}

async function cloudApi(name,args){switch(name){
case 'getAppState':return cloudLoadState();
case 'saveSettings':{const p=args[0]||{},s=state.settings;s.lowStockPercent=Math.min(100,Math.max(1,Math.round(rawNumber(p.lowStockPercent)||20)));s.stockGroupMode=p.groupMode==='category'?'category':'alphabet';s.kgStep=[0.1,0.2,0.3,0.4,0.5].includes(rawNumber(p.kgStep))?rawNumber(p.kgStep):0.1;s.stockColumns={unit:!!p.showUnit,weeklyTarget:!!p.showWeeklyTarget,remaining:!!p.showRemaining,toBuy:!!p.showToBuy,lastPurchase:!!p.showLastPurchase,status:!!p.showStatus};cloudRecompute();return cloudPersist()}
case 'setAlmostEmpty':{const[id,value]=args,p=state.products.find(x=>x.productId===id);if(!p)throw new Error('Продукт не найден');p.almostEmpty=p.unit==='шт.'&&rawNumber(p.currentStock)>0&&!!value;cloudRecomputeProduct(p);cloudSyncAutomaticBasket(false);return cloudPersist()}
case 'buildBasketFromInventory':{const items=Array.isArray(args[0])?args[0]:[];items.forEach(it=>{const p=state.products.find(x=>x.productId===it.productId);if(!p)return;p.currentStock=cloudQty(it.currentStock,p.unit);p.almostEmpty=p.unit==='шт.'&&p.currentStock>0&&!!it.almostEmpty;p.stockCheckedAt=cloudIsoDate();cloudRecomputeProduct(p)});cloudSyncAutomaticBasket(true);return cloudPersist()}
case 'saveProduct':{const payload=args[0]||{};let p=payload.productId?state.products.find(x=>x.productId===payload.productId):null;if(!p){p={productId:cloudId('PRD'),name:'',category:'',pack:'шт.',weeklyTarget:1,daysSupply:'',homeStatus:'есть достаточно',lastPurchase:'',forecastEnd:'',mainStore:'',price:'',active:'да',note:'',currentStock:0,stockCheckedAt:cloudIsoDate(),almostEmpty:false};state.products.push(p)}const u=cloudUnit(payload.pack||p.pack||p.unit);if(payload.name!=null&&payload.name!=='')p.name=String(payload.name).trim();if(payload.category!=null)p.category=payload.category;p.pack=p.unit=u;if(payload.daysSupply!==''&&payload.daysSupply!=null)p.daysSupply=Math.max(0,rawNumber(payload.daysSupply));if(payload.weeklyTarget!==''&&payload.weeklyTarget!=null)p.weeklyTarget=Math.max(cloudMinQty(u),cloudQty(payload.weeklyTarget,u));if(payload.currentStock!==''&&payload.currentStock!=null)p.currentStock=cloudQty(payload.currentStock,u);if(payload.price!==''&&payload.price!=null)p.price=Math.max(0,rawNumber(payload.price));if(payload.note!=null)p.note=payload.note;if(payload.active!=null&&payload.active!=='')p.active=payload.active;if(u!=='шт.')p.almostEmpty=false;cloudRecomputeProduct(p);cloudSyncAutomaticBasket(false);return cloudPersist()}
case 'addOrCreateBasketItem':{const payload=args[0]||{},nm=String(payload.name||'').trim();if(!nm)throw new Error('Введите название товара');let p=state.products.find(x=>String(x.name).trim().toLowerCase()===nm.toLowerCase());if(!p){const u=cloudUnit(payload.pack);p={productId:cloudId('PRD'),name:nm,category:payload.category||'',pack:u,unit:u,daysSupply:Math.max(0,rawNumber(payload.daysSupply)),weeklyTarget:Math.max(cloudMinQty(u),cloudQty(payload.weeklyTarget||(u==='кг'?1:1),u)),currentStock:0,price:payload.price===''||payload.price==null?'':Math.max(0,rawNumber(payload.price)),active:'да',note:'',almostEmpty:false,stockCheckedAt:cloudIsoDate(),lastPurchase:'',forecastEnd:'',mainStore:''};state.products.push(p);cloudRecomputeProduct(p)}else if(payload.price!==''&&payload.price!=null)cloudUpsertPrice(p,payload.price,state.settings.basketStoreId);const qty=(payload.qty===''||payload.qty==null)?Math.max(cloudStep(p.unit),rawNumber(p.recommendedQty)||rawNumber(p.weeklyTarget)||cloudStep(p.unit)):cloudQty(payload.qty,p.unit);cloudAddManualProductToBasket(p,qty,payload.price);cloudRecompute();return cloudPersist()}
case 'saveBasketDraft':cloudApplyBasketDraft(args[0]);return cloudPersist();
case 'completePurchase':{const req=args[0]||{};if(req.draft)cloudApplyBasketDraft(req.draft);cloudRecompute();const basket=state.basket.filter(i=>rawNumber(i.qty)>0);if(!basket.length)throw new Error('Корзина пуста');const pct=Math.min(100,Math.max(0,rawNumber(req.cashbackPercent))),cap=Math.max(0,rawNumber(req.cashbackLimit)),planned=Math.round((basket.reduce((s,i)=>s+rawNumber(i.qty)*rawNumber(i.unitPrice),0)+Number.EPSILON)*100)/100,key=state.settings.basketStoreId||'NO_STORE',ov=(req.actualsByStore||{})[key]||{},actual=(ov.actualTotal===''||ov.actualTotal==null)?planned:Math.max(0,rawNumber(ov.actualTotal)),discount=Math.max(0,rawNumber(ov.discount)),cashback=Math.round(((cap>0?Math.min(actual*pct/100,cap):actual*pct/100)+Number.EPSILON)*100)/100,st=state.stores.find(s=>s.storeId===state.settings.basketStoreId),purchaseId=cloudId('BUY'),date=cloudIsoDate(),note=pct>0?`Кэшбэк ${pct}% · ${cap>0?'лимит '+cap+' ₽':'без лимита'}`:'';state.purchases.unshift({purchaseId,date,month:date.slice(0,7),storeId:st?.storeId||'',storeName:st?.name||'Без магазина',plannedTotal:planned,actualTotal:actual,discount:discount||'',expectedCashback:cashback,actualCashback:cashback,netSpend:Math.round((actual-cashback+Number.EPSILON)*100)/100,comment:note});basket.forEach(i=>{state.purchaseItems.push({purchaseItemId:cloudId('ITM'),purchaseId,productId:i.productId,name:i.name,qty:i.qty,unitPrice:i.unitPrice||'',sum:i.sum||''});const p=state.products.find(x=>x.productId===i.productId);if(p){p.currentStock=cloudQty(rawNumber(p.currentStock)+rawNumber(i.qty),p.unit);p.lastPurchase=date;p.stockCheckedAt=date;p.almostEmpty=false;p.forecastEnd=rawNumber(p.daysSupply)>0&&rawNumber(p.currentStock)>0?cloudAddDays(date,rawNumber(p.daysSupply)*rawNumber(p.currentStock)):'';cloudRecomputeProduct(p)}});state.basket=[];state.basketRemoved=[];cloudRecompute();return cloudPersist('purchase-'+date)}
case 'saveStore':{const p=args[0]||{};let s=p.storeId?state.stores.find(x=>x.storeId===p.storeId):null;if(!s){s={storeId:cloudId('STR'),name:'',type:'',active:'да',note:''};state.stores.push(s)}if(p.name!=null)s.name=p.name;if(p.type!=null)s.type=p.type;if(p.note!=null)s.note=p.note;if(p.active!=null&&p.active!=='')s.active=p.active;return cloudPersist()}
case 'saveCashback':return state;
case 'setBasketStore':state.settings.basketStoreId=args[0]||'';state.basketStoreId=state.settings.basketStoreId;return cloudPersist();
default:throw new Error('Неизвестная операция: '+name)}}
